name: hava
description: اپلیکیشن هواشناسی فارسی، مینیمال و مبتنی بر داده واقعی.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  intl: ^0.20.2
  shamsi_date: ^1.0.4
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  flutter_riverpod: ^3.0.0
  dynamic_color: ^1.8.1
  flutter_map: ^8.3.2
  flutter_map_cache: ^2.1.0
  dio_cache_interceptor: ^4.0.7
  http_cache_file_store: ^2.0.2
  path_provider: ^2.1.5
  latlong2: ^0.10.1
  flutter_local_notifications: ^22.3.1
  workmanager: ^0.10.0+1
  home_widget: ^0.9.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/branding/hava_logo.png
    - assets/data/iran_locations.json
